org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.1]
neoforge_version=21.1.213
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=create_access_denied
mod_name=Create: Access Denied
mod_license=MIT
mod_version=0.0.2
mod_group_id=net.fivew14.addons
mod_authors=5w14
mod_description=Simple access management for your logistics network
create_version=6.0.7
ponder_version=1.0.64
parchment_mappings_version=2024.11.17
parchment_minecraft_version=1.21.1
